### ISSUE TITLE
Use #filter instead of #forEach

### ISSUE THREAD

**Issue by jridgewell** [trezy/Scheduler.js#3]
You can use `Array#filter` [here](https://github.com/trezy/Scheduler.js/blob/master/Scheduler.js#L82-L86).

**Comment by trezy** [comment]
Instead of using `Array#filter`, I switched everything back to using basic `for` loops. [Here's a jsperf showing the pretty drastic performance difference.](http://jsperf.com/array-filter-vs-array-foreach)

**Comment by jridgewell** [comment]
Yup, that's true. You can help it a little more by caching `this.tasks` instead of doing a prop lookup every time.

``` js
var tasks = this.tasks;
for (var i = 0; i < tasks.length; i++) {
  var task = tasks[i];
  // ...
}
```
