### ISSUE TITLE
Avoid creating new function instances

### ISSUE THREAD

**Issue by jridgewell** [trezy/Scheduler.js#4]
Since `#_startLoop` is the performance critical path, you can optimize it a bit by avoiding new [function](https://github.com/trezy/Scheduler.js/blob/master/Scheduler.js#L125-L127) [instances](https://github.com/trezy/Scheduler.js/blob/master/Scheduler.js#L129-L131).

Instead, bind `#_startLoop` to the instance in the constructor:

``` js
Scheduler = function Scheduler () {
  this.tasks = [];
  this._startLoop = this._startLoop.bind(this);
  this._startLoop();
}
```

And hoist your loop either onto the prototype or into the closure:

``` js
function caller ( taskObject ) {
    taskObject.task.call( taskObject.context );
}

Scheduler.prototype._startLoop = function _startLoop () {
  // ...
  schedule.tasks.forEach(caller);
};
```

**Comment by trezy** [comment]
I get the hoisting part but I don't understand what the benefit of `this._startLoop = this._startLoop.bind(this);` would be?

**Comment by jridgewell** [comment]
You eliminate the new function on [L137-139](https://github.com/trezy/Scheduler.js/blob/master/Scheduler.js#L137-L139):

``` js
requestAnimationFrame(schedule._startLoop);
```

**Comment by trezy** [comment]
Oh, snap. @jridgewell, you've just changed my life forever.
